notifications:
  email: false

os: linux
sudo: false
addons:
  apt:
    packages:
      - texlive-full

script:
  - make travis-build -C src/eng
  - make travis-build -C src/svk
  - make travis-build -C src/cze
